export default {
  auth: (state) => state.auth,
  user: (state) => state.user,
  currentStatus: (state) => state.currentStatus,
  defaultStatus: (state) => state.defaultStatus,
  allTeamMembers: (state) => state.allTeamMembers,
  allGroupTextMembers: (state) => state.allGroupTextMembers,
  messages: (state) => state.messages,
  unReadMsgCounter: (state) => state.unReadMsgCounter,
  folders: (state) => state.folders,
  messageSearchFilter: (state) => state.messageSearchFilter,
  taskFilter: (state) => state.taskFilter,
  tasks: (state) => state.tasks,
  contacts: (state) => state.contacts,
  contact: (state) => state.contact,
  allTags: (state) => state.allTags,
  schedules: (state) => state.schedules,
  nextStatus: (state) => state.nextStatus,
  todaySchedules: (state) => state.todaySchedules,
  allStatus: (state) => state.allStatus,
  allStatusMessages: (state) => state.allStatusMessages,
  allStatusCallbackMessages: (state) => state.allStatusCallbackMessages,
  allNotificationSetting: (state) => state.allNotificationSetting,

  isMainTutorial: (state) => state.isMainTutorial,
  isMessageTutorial: (state) => state.isMessageTutorial,
}
